### ISSUE TITLE
Cool project! However, in the IAT section, you are calling LoadLibraryA but not using recursion to fully implement LoadLibrary.

### ISSUE THREAD

**Issue by ahron-chet** [adamhlt/Manual-DLL-Loader#1]
Cool project! However, in the IAT section, you are calling LoadLibraryA but not using recursion to fully implement LoadLibrary.

**Comment by adamhlt** [comment]
I already try to recursively import all dll depencies using the custom loadlibrary, but it will not work with all windows dll, like user32.dll. Can't figure out why.

**Comment by CycloneRing** [comment]
@adamhlt You can check this project to see what they did https://github.com/bb107/MemoryModulePP

**Comment by adamhlt** [comment]
@CycloneRing Thanks I will take a look and try to improve the project.
